### ISSUE TITLE
TypeChecker crashes on encountering ObjectType

### ISSUE THREAD

**Issue by MalteRichert** [yannickkirschen/mini-java#11]
Encountered this exception:
```
Exception in thread "main" de.dhbw.compiler.typecheck.SyntaxException: Unexpected type: NiceClass
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:91)
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:29)
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:44)
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:25)
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:44)
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:25)
	at de.dhbw.compiler.typecheck.MethodChecker.check(MethodChecker.java:36)
	at de.dhbw.compiler.typecheck.ClassChecker.check(ClassChecker.java:59)
	at de.dhbw.compiler.typecheck.TypeCheck.check(TypeCheck.java:25)
	at de.dhbw.compiler.Compiler.main(Compiler.java:26)
```

on running `Compiler` on the latest version of test-and-fix branch with the following input:
```
class NiceClass {
    int i;

    NiceClass(){}

    int do() {
        NiceClass o = new NiceClass();

        return o;
    }
}
```

**Comment by yannickkirschen** [comment]
I think that's not a bug, it's a feature. We can't use a variable of its own type because we don't haven't checked it to that point. Am I right, @nichtLehdev ? Or have I forgot something?

**Comment by MalteRichert** [comment]
> I think that's not a bug, it's a feature. We can't use a variable of its own type because we don't haven't checked it to that point. Am I right, @nichtLehdev ? Or have I forgot something?

If that is not supposed to work, is there any implementation of New or any constructor call that should work?

**Comment by yannickkirschen** [comment]
Good question xD. I'll have a look at it tomorrow

**Comment by nichtLehdev** [comment]
@yannickkirschen Yeah I think we left that out on purpose, but Malte has a point.. We did implement new after all.
Think fix shouldn't be too hard, please lmk if I can help. I'm in office for the rest of the week tho so can't really do much, but will try to be as helpful as I can!
