### ISSUE TITLE
Binary operation with equal types is not accepted in TypeChecker

### ISSUE THREAD

**Issue by MalteRichert** [yannickkirschen/mini-java#13]
```
class NiceClass {
    int do() {
        {
            int v = 2 * 3;
            }
        return v;
    }
}
```
produces
```
Exception in thread "main" de.dhbw.compiler.typecheck.TypeException: Incompatible types in binary expression: INTEGER and INTEGER
	at de.dhbw.compiler.typecheck.ExpressionChecker.check(ExpressionChecker.java:79)
	at de.dhbw.compiler.typecheck.ExpressionChecker.check(ExpressionChecker.java:24)
	at de.dhbw.compiler.typecheck.StatementExpressionChecker.check(StatementExpressionChecker.java:50)
	at de.dhbw.compiler.typecheck.StatementExpressionChecker.check(StatementExpressionChecker.java:37)
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:107)
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:33)
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:44)
	at de.dhbw.compiler.typecheck.StatementChecker.check(StatementChecker.java:25)
	at de.dhbw.compiler.typecheck.MethodChecker.check(MethodChecker.java:36)
	at de.dhbw.compiler.typecheck.ClassChecker.check(ClassChecker.java:59)
	at de.dhbw.compiler.typecheck.TypeCheck.check(TypeCheck.java:25)
	at de.dhbw.compiler.Compiler.main(Compiler.java:26)
```

**Comment by nichtLehdev** [comment]
Ok, für den Hab ich sogar ne erklärung. Wir sind von vollen Namen also java.lang.Integer ausgegangen. Bekommen wir immer nur Integer, Boolean? @MalteRichert

**Comment by Rex2002** [comment]
```
for (int i = 0; i < method.parameters.size(); i++) {
    Expression argument = expressionChecker.check(methodCall.args.get(i));

    <--old-- if (!method.parameters.get(i).getType().getName().equals(argument.getType().getName())) { ---->
    if (!method.parameters.get(i).getType().equals(argument.getType())) {
        throw new TypeException("Type mismatch: %s and %s for argument %d in method %s", method.parameters.get(i).getType().getName(), argument.getType().getName(), i, method.name);
    }
  }
```
(copied from your 70b3592)

does this also work for non-PrimitiveType? because if we do .equals on ObjectType, wouldn't this required us to override the equals-method to check that the names are the same?

**Comment by nichtLehdev** [comment]
Ur right with that @Rex2002 . Already implementing a fix (just running equals on the .getName()) to resolve #11
