### ISSUE TITLE
CodeGen seems to have a problem with negative integer

### ISSUE THREAD

**Issue by MalteRichert** [yannickkirschen/mini-java#19]
Encountering this:
```
Exception in thread "main" java.lang.IllegalArgumentException: not allowed here: de.dhbw.compiler.ast.expressions.JInteger@6be46e8f
	at de.dhbw.compiler.codegeneration.MethodCodeVisitor.visitExpression(MethodCodeVisitor.java:309)
	at de.dhbw.compiler.ast.expressions.Unary.accept(Unary.java:25)
	at de.dhbw.compiler.codegeneration.MethodCodeVisitor.visit(MethodCodeVisitor.java:130)
	at de.dhbw.compiler.ast.stmtexprs.Assign.accept(Assign.java:25)
	at de.dhbw.compiler.codegeneration.MethodCodeVisitor.visit(MethodCodeVisitor.java:107)
	at de.dhbw.compiler.ast.statements.StmtExprStmt.accept(StmtExprStmt.java:22)
	at de.dhbw.compiler.codegeneration.MethodCodeVisitor.lambda$visit$2(MethodCodeVisitor.java:60)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at de.dhbw.compiler.codegeneration.MethodCodeVisitor.visit(MethodCodeVisitor.java:60)
	at de.dhbw.compiler.ast.statements.Block.accept(Block.java:23)
	at de.dhbw.compiler.codegeneration.MethodCodeVisitor.lambda$visit$2(MethodCodeVisitor.java:60)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at de.dhbw.compiler.codegeneration.MethodCodeVisitor.visit(MethodCodeVisitor.java:60)
	at de.dhbw.compiler.ast.statements.Block.accept(Block.java:23)
	at de.dhbw.compiler.codegeneration.MethodCodeVisitor.visit(MethodCodeVisitor.java:50)
	at de.dhbw.compiler.codegeneration.CodeGenVisitor.visitClass(CodeGenVisitor.java:34)
	at de.dhbw.compiler.codegeneration.CodeGenerator.generateCode(CodeGenerator.java:10)
	at de.dhbw.compiler.Compiler.main(Compiler.java:24)
```
upon inputting this:
```
"""
    class Leer {

        void boomethod(int i){
            int test = -42;
        }
    }
"""
```

**Comment by MalteRichert** [comment]
On the current version of `TypeCheck-fix`

**Comment by Rex2002** [comment]
Not sure if that is codegen / if it makes sense to treat this in codegen, 
I would say it is simpler to parse a negative number actually as a negative number rather than a Unary Operation with the Operator "-". 
The parsing (I think) would be a quick fix by changing the grammar in line 118 from 
`number: Numeral+;` to `number: Sign? Numeral+;`   (and removing it from the Unary)
otherwise we would have to add mimic a `0 - intValue` everytime a negative number occurs

**Comment by Rex2002** [comment]
now interpreting ` var = -var` as `var = 0 - var` (at parser level)
